# Generated by Django 5.2.1 on 2026-02-13 04:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('block_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('block_type', models.CharField(choices=[('deep_work', 'Deep Work'), ('meeting', 'Meeting'), ('break', 'Break'), ('task', 'Task')], default='task', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'time_blocks',
                'ordering': ['block_date', 'start_time'],
            },
        ),
    ]
