# Generated by Django 5.2.1 on 2026-02-13 04:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkin_date', models.DateField()),
                ('energy_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('reflection', models.TextField(blank=True)),
                ('tasks_planned', models.IntegerField(default=0)),
                ('tasks_completed', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'daily_checkins',
                'ordering': ['-checkin_date'],
            },
        ),
        migrations.CreateModel(
            name='HabitStreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('streak_date', models.DateField()),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('completed_today', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'habit_streaks',
                'ordering': ['-streak_date'],
            },
        ),
    ]
