# Generated by Django 5.2.1 on 2026-02-13 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habits', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycheckin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='habitstreak',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_streaks', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='habitstreak',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_streaks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dailycheckin',
            unique_together={('user', 'checkin_date')},
        ),
        migrations.AddIndex(
            model_name='habitstreak',
            index=models.Index(fields=['user', 'task', 'streak_date'], name='habit_strea_user_id_32e851_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='habitstreak',
            unique_together={('user', 'task', 'streak_date')},
        ),
    ]
