# Generated by Django 5.2.1 on 2026-02-13 04:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('session_type', models.CharField(choices=[('pomodoro', 'Pomodoro'), ('custom', 'Custom')], default='pomodoro', max_length=10)),
                ('target_minutes', models.IntegerField(default=25)),
                ('distraction_log', models.JSONField(blank=True, default=list)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'focus_sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
